development:
  password: cf18244bdffd9e812b98c91e611e03cd
  theme_id: "127982338248"
  store: diff-theme-training.myshopify.com
npm installdevelopment:
  password: cf18244bdffd9e812b98c91e611e03cd
  theme_id: "127982338248"
  store: diff-theme-training.myshopify.com
